### ISSUE TITLE
Visualization of the problem

### ISSUE THREAD

**Issue by git0929** [BlueCat-de/SDM#4]
Hello, your code is great, but I have a problem that I can't generate an image on the visualization, and it still doesn't work after trying to change it, so I ask you to see how this error should be fixed.

Traceback (most recent call last):
  File "/home/hou/SDM/Scripts/main_NSG.py", line 440, in <module>
    absl.app.run(main)
  File "/home/hou/anaconda3/envs/SDM/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/hou/anaconda3/envs/SDM/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/hou/SDM/Scripts/main_NSG.py", line 143, in main
    wandb_logger = WandbLogger(config=FLAGS.logging, variant=variant)
TypeError: __init__() missing 1 required positional argument: 'seed'

**Comment by BlueCat-de** [comment]
Thanks for bringing this up. We fixed this issue in the latest [version](https://github.com/BlueCat-de/SDM/commit/44220cb97cb0222b0a7fab8d2bb75cf00b4edb5b) .
